### ISSUE TITLE
Default Cookbook recipe don't work with chef-client version 11.10

### ISSUE THREAD

**Issue by tuxinaut** [bflad/chef-jira#10]
The default cookbook recipe don't workt with the (last) chef-client version 11.10

Error message

```
java_ark[jdk] (java::oracle line 47)

Failed to extract file jdk-7u25-linux-x64.tar.gz!
```

Sorry for the less details my terminal eat the error messages :smile: I can ran the recipe tomorrow agian an amend more details.

**Comment by bflad** [comment]
For those still following along, I'd suggest switching over to the much better and supported afklm fork, which is now officially the `jira` cookbook: https://supermarket.chef.io/cookbooks/jira - see #22 for discussion and details.
