### ISSUE TITLE
[meta] Adding new maintainers

### ISSUE THREAD

**Issue by patcon** [bflad/chef-jira#20]
Hey @bflad, how do you feel about adding more maintainers to this repo? I'd like to update some things if at all possible. Glad to help if you're willing to add me :)

Thanks!

**Comment by gsreynolds** [comment]
:+1:

**Comment by bflad** [comment]
I'd suggest switching over to the much better and supported afklm fork, which is now officially the `jira` cookbook: https://supermarket.chef.io/cookbooks/jira - see #22 for discussion and details. Thanks for your help though in the past.
