### ISSUE TITLE
Apache Install/Config should be configurable

### ISSUE THREAD

**Issue by maikihde** [bflad/chef-jira#9]
Hi,

the installation of the jira::apache2 recipe and the Apache configuration should be made optional via attributes. I need to install jira on a Server that is behind a central loadbalancer which also does SSL termination. Therefore I do not need apache to be configured before Jira. It would be really cool if this could be configurable via an attribute and/or via data bag...

Kind Regards
Maik

**Comment by bflad** [comment]
For those still following along, I'd suggest switching over to the much better and supported afklm fork, which is now officially the `jira` cookbook: https://supermarket.chef.io/cookbooks/jira - see #22 for discussion and details.
